<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>

---

## Домашнее задание: библиотека Numpy и линейная алгебра. Решение


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [235]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((4, 4))
b = np.random.sample((4, 4))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print(a)
print(b.shape)
# ========

[[6.24325713e-01 9.00160626e-01 2.54571378e-01 2.87155299e-01]
 [6.43046220e-02 5.64999186e-01 3.50306903e-01 7.36430950e-01]
 [3.52815575e-04 5.05980458e-01 2.41024401e-01 8.74936346e-01]
 [2.87738913e-01 7.11680951e-01 7.80794185e-01 5.73633681e-01]]
(4, 4)


In [236]:
def mult(a, b):
    # здесь напишите перемножение матриц без 
    # использования NumPy и выведите результат
    c = []
    d = []
    e = 0
    for i in range(0, a.shape[0]):    
        for j in range(0, b.shape[1]):
            for k in range(0, a.shape[1]):
                e = a[i][k] * b[k][j] + e
            c.append(e)
            e = 0
        d.append(c)
        c = []
    return d

In [237]:
def np_mult(a, b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат
    
    result = np.dot(a,b)
    return result

In [240]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

Wall time: 0 ns


In [241]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

Wall time: 0 ns


In [242]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

0.0

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [243]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.24817343 0.32627598 0.43954471] [0.1428392  0.37810871 0.15434655]


In [247]:
def scalar_product(a,b):
    result = sum(a[i]*b[i] for i in range(3) )
    return result

In [250]:
def np_scalar_product(a,b):
    result = np.dot(a,b)
    return result

In [251]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

Wall time: 0 ns
Wall time: 105 ms


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [347]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    return sum(x for x in a.diagonal() if x%2==0)

In [348]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[8, 7, 5, 3, 8],
       [1, 4, 6, 3, 7],
       [2, 8, 4, 7, 8],
       [6, 9, 8, 8, 1],
       [4, 5, 7, 8, 5]])

In [349]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

Wall time: 0 ns


24

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, ..., x_n)$ массива $X$ строит строчку $s = (s_1, s_2, ..., s_n)$, где $s_k = x_1 + ... + x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку `numpy` (вам поможет функция `cumsum`). Выходом функции должен быть двумерный массив той же формы, что и $X$. 

In [382]:
# функция, решающая задачу с помощью NumPy
def cumsum(A):
    c = []
    for x in A:
        c.append(np.cumsum(x))
    return np.array(c)


In [383]:
%%time
A = np.array([[0,1,2], [3,2,1]])
print(A)
S2 = cumsum(A)
print(S2)

[[0 1 2]
 [3 2 1]]
[[0 1 3]
 [3 5 6]]
Wall time: 1.11 ms


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив xс преобразованным xи вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [0]:
# функция, решающая задачу с помощью NumPy
from copy import copy
def np_transformation(X, a=1):
    #YOUR CODE

In [0]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy 
%time S2 = np_transformation(X, 5)

CPU times: user 159 µs, sys: 0 ns, total: 159 µs
Wall time: 183 µs


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [0]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    #YOUR CODE

In [0]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

%time x, num = np_encode(X)

CPU times: user 51 µs, sys: 2 µs, total: 53 µs
Wall time: 58.7 µs
