<p style="align: center;"><img align=center src="https://s8.hostingkartinok.com/uploads/images/2018/08/308b49fcfbc619d629fe4604bceb67ac.jpg" width=500 height=450/></p>

<h3 style="text-align: center;"><b>Физтех-Школа Прикладной математики и информатики (ФПМИ) МФТИ</b></h3>

---

## Домашнее задание: библиотека Numpy и линейная алгебра. Решение


In [1]:
import numpy as np
import random
import scipy.stats as sps

### Numpy

### Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета ***numpy*** и с ним.

In [2]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов 
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),  
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((4, 4))
b = np.random.sample((4, 4))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print(a)
print(b.shape)
# ========

[[0.98548204 0.50709643 0.78427579 0.2932948 ]
 [0.24500263 0.73826887 0.49727802 0.72247516]
 [0.92383479 0.59314847 0.50230074 0.05140659]
 [0.14570599 0.41571451 0.67823994 0.20637356]]
(4, 4)


In [3]:
def mult(a, b):
    # здесь напишите перемножение матриц без 
    # использования NumPy и выведите результат
    c = []
    d = []
    e = 0
    for i in range(0, a.shape[0]):    
        for j in range(0, b.shape[1]):
            for k in range(0, a.shape[1]):
                e = a[i][k] * b[k][j] + e
            c.append(e)
            e = 0
        d.append(c)
        c = []
    return d

In [4]:
def np_mult(a, b):
    # здесь напишите перемножение матриц с
    # использованием NumPy и выведите результат
    
    result = np.dot(a,b)
    return result

In [5]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

Wall time: 0 ns


In [6]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

Wall time: 902 ms


In [7]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

0.0

### Задание 2

Вам подаются на вход два вектора `a` и `b` в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью  `NumPy` и без. Засеките время работы, как это показано в заданиях выше.

In [8]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.68391436 0.84010701 0.94097641] [0.58049951 0.33250859 0.26986707]


In [9]:
def scalar_product(a,b):
    result = sum(a[i]*b[i] for i in range(3) )
    return result

In [10]:
def np_scalar_product(a,b):
    result = np.dot(a,b)
    return result

In [11]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

Wall time: 0 ns
Wall time: 32 ms


0.0

Почему методы ***numpy*** оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

------------------

**Ответ:** Скорость вычислений вектоных и матричных операций в NumPy сильно превосходит скорость вычислений без него, по большей части потому, что функции numpy работаю с массивами данных одного типа (числовыми), это позволяет реализовать встроенные функции numpy на C/C++, что, конечно, делает numpy быстрее (функции, которые вызывает Numpy для работы с числовыми данными, сильно оптимизированы именно под эти задачи, а сам Python просто гоняет интерпретатор по циклу в таких операциях, что является чуть ли не самым большим замедлением в работе интерпретатора).

### Задание 3
Напишите функцию, которая находим сумму четных диагональных элементов квадратной матрицы. Если таких элементов нет, то вывести `0`.

In [12]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    return sum(x for x in a.diagonal() if x%2==0)

In [13]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[7, 1, 6, 1, 1],
       [2, 1, 2, 7, 7],
       [2, 5, 1, 5, 4],
       [7, 6, 1, 9, 4],
       [1, 8, 4, 2, 3]])

In [14]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

Wall time: 7 ms


0

### Задание 4
На вход дан двумерный массив $X$. Напишите функцию, которая для каждой строчки $x = (x_1, x_2, ..., x_n)$ массива $X$ строит строчку $s = (s_1, s_2, ..., s_n)$, где $s_k = x_1 + ... + x_k$, а затем выдаёт массив из построенных строчек. Используйте библиотеку `numpy` (вам поможет функция `cumsum`). Выходом функции должен быть двумерный массив той же формы, что и $X$. 

In [15]:
# функция, решающая задачу с помощью NumPy
def cumsum(A):
    c = []
    for x in A:
        c.append(np.cumsum(x))
    return np.array(c)


In [16]:
%%time
A = np.array([[0,1,2], [3,2,1]])
print(A)
S2 = cumsum(A)
print(S2)

[[0 1 2]
 [3 2 1]]
[[0 1 3]
 [3 5 6]]
Wall time: 8 ms


### Задание 5

​
Задан двумерный массив $X$. Для каждой строчки массива X необходимо сделать следующее преобразование.

Пусть дана строчка x. Необходимо построить новый массив, где все элементы с нечетными индексами требуется заменить на число a (значение по умолчанию a=1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. В конце требуется слить массив xс преобразованным xи вывести.

Напишите функцию, которая выполняет данное преобразование для каждой строчки двумерного массива X. Массив X при этом должен остаться без изменений.

Используйте библиотеку numpy.

Пример:
$X = [[100,200,300,400,500]]$ -> $[[100,a,300,a,500]]$ -> $[[500^3,a,300^3,a,100^3]]$ -> склеиваем -> $[[100,200,300,400,500,500^3,a,300^3,a,100^3]]$

​

In [2]:
# функция, решающая задачу с помощью NumPy
from copy import copy

import numpy as np

def transform(X, a=1):
    B = X.copy()
    for i in B:
        i[1::2] = a
        if len(B[0])%2 == 0:
            i[::2] = (i[-2::-2])**3
        else:
            i[::2] = (i[-1::-2])**3
    return np.hstack((X, B))

In [8]:
X = np.array( [[1,2,3,4,5], [1,2,3,4,5], [0, 2, -5, -4, 1]])
%time S2 = transform(X, 5)

Wall time: 0 ns


### Задание 6
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить. 

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [129]:
import numpy as np

def encode(a):
    count = 0
    c = [a[0]]
    for i in range(len(a)-1):
        if a[i+1] != a[i]:            
            c.append(a[i+1])
    x = np.array(c)
    k = 0
    count = 0
    d = []
    for j in range(0, len(x)):
        while x[j] == a[k]:
            k = k+1
            count = count + 1
            if k == len(a):
                 break
        d.append(count)
        count = 0
    return (x, np.array(d))

In [133]:
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = encode(X)

Wall time: 0 ns


In [96]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad